version: 1.1.5.{build}
configuration: Release
image: Visual Studio 2017
nuget:
  project_feed: true
build_script:
- ps: ./build.cmd Compile
test:
  assemblies:
    only:
    - AsyncConverter.Tests.dll